### ISSUE TITLE
Test templates locally?

### ISSUE THREAD

**Issue by jcbhmr** [devcontainers/template-starter#15]
I'd like to be able to test a devcontainer template locally. Just like the regular old code-test-commit loop that I use for _a lot_ of other projects, I'd love to do the same with a `devcontainer-feature.json`.

It seems like there's already _some_ testing that's done in the https://github.com/devcontainers/template-starter/blob/main/.github/workflows/test-pr.yaml file, but I'd love to see that pulled out into something more "runnable" rather than stuffed inside a github action. Like ./test.sh or tools/test.sh or something 🤷‍♂️

But that's just an idea. 💡

**Comment by samruddhikhandale** [comment]
That makes sense, @jcbhmr would you be interested in having a new dev container CLI command (say `devcontainer templates test`) ? Something similar to [docs/features/test.md](https://github.com/devcontainers/cli/blob/main/docs/features/test.md)

**Comment by samruddhikhandale** [comment]
Even today, we could run tests locally as mentioned in https://github.com/devcontainers/template-starter#testing-templates
However, instead of running two files, https://github.com/devcontainers/template-starter/pull/16 concats into a single file. 

Until we have a devcontainer CLI command, I think this should be helpful. Let me know if you have any other thoughts!

**Comment by jcbhmr** [comment]
> That makes sense, @jcbhmr would you be interested in having a new dev container CLI command (say `devcontainer templates test`) ? Something similar to [docs/features/test.md](https://github.com/devcontainers/cli/blob/main/docs/features/test.md)

Sounds cool!

> Even today, we could run tests locally as mentioned in https://github.com/devcontainers/template-starter#testing-templates
> However, instead of running two files, https://github.com/devcontainers/template-starter/pull/16 concats into a single file.

Very true, I didn't remember that 🤦‍♂️ -- it's stuffed into `.github/*` which kinda marks it as "not runnable" or "github meta only" in my brain 🧠 so that oopsie misunderstanding is on me.

Thanks for combining it into a single file! I'll add a `./test.sh` or `tools/test.sh` or something to my own repos to just invoke that `.github/actions/smoke-test/test.sh` script.

This solution works for me, thanks!  🙏
