### ISSUE TITLE
ℹ️  The following images have released a `new major version` to add support for `debian:bookworm` ℹ️

### ISSUE THREAD

**Issue by PKhamorn302531** [devcontainers/template-starter#21]
ℹ️  The following images have released a `new major version` to add support for `debian:bookworm` ℹ️ 

ℹ️  We’d recommend re-pinning to the new major versions to continue receiving security patches and updates

1. [base-debian](https://github.com/devcontainers/images/blob/main/src/base-debian/history/1.0.0.md)
2. [cpp](https://github.com/devcontainers/images/blob/main/src/cpp/history/1.0.0.md)
3. [java-8](https://github.com/devcontainers/images/blob/main/src/java-8/history/2.0.0.md)
4. [java](https://github.com/devcontainers/images/blob/main/src/java/history/1.0.0.md)
5. [javascript-node](https://github.com/devcontainers/images/blob/main/src/javascript-node/history/1.0.0.md)
6. [php](https://github.com/devcontainers/images/blob/main/src/php/history/1.0.0.md)
7. [rust](https://github.com/devcontainers/images/blob/main/src/rust/history/1.0.0.md)

_Originally posted by @samruddhikhandale in https://github.com/devcontainers/images/issues/607#issuecomment-1593580388_

**Comment by samruddhikhandale** [comment]
Looks like an accident, closing. Opened https://github.com/devcontainers/template-starter/pull/22 to update the dev container.
